DCUSnSLab/DCU_Online_Judge_Frontend

src/i18n/oj/ko-KO.js, src/pages/admin/api.js, src/pages/oj/App.vue, src/pages/oj/components/NavBar.vue, src/pages/oj/components/Pagination.vue, src/pages/oj/views/general/Home.vue, src/pages/oj/views/lecture/children/ContestProblemList.vue, src/pages/oj/views/user/Register.vue, src/pages/oj/views/user/UserHome.vue
=> Dcuc 75 improve register autodata

src/i18n/index.js
지정한 언어에 번역이 없을 때 보여줄 언어 지정 (한국어로 지정함)
=> [GEN-13] Language to show when there is no translation 

Dockerfile, jenkinsfile, src/pages/oj/api.js, start.sh
=> [GEN-143] jenkins file updated - deploy over ssh

src/pages/admin/views/lecture/Lecture.vue, src/pages/oj/views/lecture/CourseList.vue
아래와 같이 수정
- 수강 과목
- 5년전 ~현재 년도
- 강의 개설 페이지
- 3년전~현재 년도에서 2년후
=> [GEN-208] 강의 개설 년도 자동 생성

src/i18n/oj/en-US.js, src/i18n/oj/ko-KR.js, src/pages/oj/api.js, src/pages/oj/views/submission/SubmissionDetails.vue
**GitHub에 작성한 코드 업로드할 수 있는 기능 추가**
=> [GEN-215] add upload GitHub

src/pages/oj/views/general/Home.vue
- 1920*1080
- 개인정보 변경 안내문 기간을 3~4월에서 3뭘만 나오도록 변경함
=> [GEN-256] 포스터 패널 사이즈 조절 및 개인정보 변경 안내문 기간 변경

src/pages/admin/api.js, src/pages/admin/views/problem/Problem.vue, src/pages/oj/components/CodeMirror.vue, src/pages/oj/views/problem/Problem.vue
=> Gen 216 code run feature

src/pages/admin/views/problem/Problem.vue, src/pages/oj/views/problem/Problem.vue
=> Gen 216 code run feature (develop branch)

src/pages/admin/views/problem/Problem.vue
=> GEN-216_code_run_feature (develop branch)

src/pages/oj/api.js, src/pages/oj/views/contest/ContestDetail.vue, src/pages/oj/views/contest/children/ContestProblemList.vue, src/pages/oj/views/lecture/LectureContestDetail.vue, src/pages/oj/views/lecture/LectureContestExit.vue, src/pages/oj/views/lecture/children/ContestProblemList.vue, src/pages/oj/views/problem/Problem.vue, src/store/modules/user.js
Gen 288 lecture contest exit (develop branch)
=> Gen 288 lecture contest exit (develop branch)

src/pages/oj/views/contest/ContestDetail.vue, src/pages/oj/views/lecture/LectureContestDetail.vue, src/pages/oj/views/problem/Problem.vue
Hide non-subject contest exit button
=> GEN-288_lecture-contest-exit

src/i18n/oj/en-US.js, src/i18n/oj/ko-KR.js
아래 단어가 ko-KR, en-US 파일에 이름이 다르게 되어있어 영어로 뜨는 문제 해결 및 By -> by로 변경
'DCU Code 사용 매뉴얼 (학생용)',
'DCU Code 소개 영상',
'진행중인 실습 및 과제',
'실습/과제',
=> GEN-164 modified Korean and Eng

src/pages/oj/views/lecture/CourseList.vue
=> GEN-211_CourseList.vue_semester_update (develop branch)

src/pages/admin/views/contest/Contest.vue, src/pages/admin/views/contest/ContestList.vue, src/pages/admin/views/general/User.vue, src/pages/admin/views/lecture/Lecture.vue, src/pages/admin/views/lecture/LectureList.vue, src/pages/admin/views/problem/Problem.vue, src/pages/admin/views/problem/ProblemList.vue, src/pages/oj/views/contest/ContestList.vue, src/pages/oj/views/lecture/CourseList.vue, src/pages/oj/views/lecture/LectureList.vue, src/pages/oj/views/problem/ProblemList.vue, src/pages/oj/views/qna/ProblemQnAList.vue
=> GEN-309_pagination-router (develop branch)

src/pages/admin/views/lecture/Lecture.vue
=> GEN-252_AdminList_get_fix (develop branch)

src/pages/admin/api.js, src/pages/admin/views/contest/AddLectureCopy.vue, src/pages/admin/views/contest/AddPublicContest.vue
=> GEN-214_copy_contest_lecture_fix (develop branch)

src/pages/admin/views/contest/ContestList.vue, src/pages/admin/views/general/User.vue, src/pages/admin/views/lecture/LectureList.vue, src/pages/admin/views/problem/ProblemList.vue, src/pages/oj/views/contest/ContestList.vue, src/pages/oj/views/lecture/CourseList.vue, src/pages/oj/views/lecture/LectureList.vue, src/pages/oj/views/qna/ProblemQnAList.vue
=> Gen-309_pagination router(develop branch)

src/pages/admin/views/contest/AddLectureCopy.vue, src/pages/admin/views/contest/AddPublicContest.vue
- 과목 전체  복사, 실습 가져오기 할 때, 현재 년도까지 자동으로 추가되도록 수정
- 2019년도부터 현재 년도까지 출력하도록 설정
=> GEN-442 modified selete years

src/pages/admin/views/lecture/LectureList.vue, src/pages/admin/views/problem/Problem.vue, src/pages/admin/views/problem/ProblemList.vue
=> GEN-443 Add search in problem list

.eslintrc.js, src/pages/oj/api.js, src/pages/oj/views/container/Container.vue, src/pages/oj/views/user/Login.vue
=> GEN-313_add_webssh(develop)

src/i18n/oj/en-US.js, src/i18n/oj/ko-KR.js, src/pages/oj/views/user/Register.vue
ID : 소문자, 숫자만 사용 가능
이름 : 숫자 사용 불가능
=> GEN-431 ID, 이름 생성 규칙

src/pages/oj/views/problem/Problem.vue
=> GEN-420_fix_run_code

src/pages/oj/api.js, src/pages/oj/views/lecture/LectureContestDetail.vue, src/pages/oj/views/lecture/LectureContestExit.vue, src/pages/oj/views/lecture/children/ContestProblemList.vue, src/pages/oj/views/problem/Problem.vue
=> GEN-510_fix_test_exit (develop)

src/pages/oj/views/problem/Problem.vue
GEN-420 problem.vue fix (develop branch)
=> GEN-420 problem.vue fix (develop branch)

src/pages/oj/views/problem/Problem.vue
복사 방지를 위한 기능 추가
- 문제 복사를 시도하면 임의의 문제 3개 중 하나 랜덤으로 복사
- 창을 벗어나면 블러 처리
=> Gen 546 anti copy

src/pages/oj/views/container/Container.vue
=> GEN-552_Xterm (develop)

src/pages/oj/api.js, src/pages/oj/views/lecture/LectureContestDetail.vue, src/pages/oj/views/lecture/LectureContestExit.vue
Reverts DCUSnSLab/DCU_Online_Judge_Frontend#120
=> Revert "Gen 572"
